### ISSUE TITLE
add default to `?` optional struct fields 

### ISSUE THREAD

**Issue by nilslice** [dylibso/xtp-zig-bindgen#8]
Until we have (?) `required` back in the schema, we should add `null` defaults to the optional struct fields

**Comment by chrisdickinson** [comment]
Related: https://github.com/dylibso/xtp-cpp-bindgen/issues/3 (and cc'ing @bhelx for visibility)

**Comment by bhelx** [comment]
Just clearing some decks now and required will land soon. we can collaborate tomorrow on how to handle it in zig bindgen

**Comment by nilslice** [comment]
@bhelx - i'll ship a quick fix for this pre-required so it's usable in the immediate term!
